### ISSUE TITLE
python main.py报错

### ISSUE THREAD

**Issue by vagile-cn** [Jiahonzheng/JGM-Automator#13]
vagile@VagileMBP:/github/JGM-Automator$ python main.py
Traceback (most recent call last):
  File "main.py", line 2, in <module>
    from automator import Automator
  File "/Users/vagile/github/JGM-Automator/automator.py", line 16
    def __init__(self, device: str, targets: dict):
                             ^
SyntaxError: invalid syntax
vagile@VagileMBP:~/github/JGM-Automator$

求解

**Comment by BackTrackCRoot** [comment]
用Python3 这是Python3的语法

**Comment by vagile-cn** [comment]
也就是说我之前的依赖也需要用python安装吗？ @BackTrackCRoot

**Comment by TsingWei** [comment]
对, 如果你电脑里同时有py2和py3的话, 依赖库是不共享的,需要使用pip3命令给py3安装依赖
