### ISSUE TITLE
运行之后无法挂机

### ISSUE THREAD

**Issue by SQNRT** [Jiahonzheng/JGM-Automator#17]
采用1920*1080 16:9分辨率
可以正常启动软件，但是软件会误触公告，导致无法正常工作，也无法检查火车状态。

**Comment by TsingWei** [comment]
有可能app界面并不是全屏运行,毕竟大部分位置都是手动写死的, 后期可能会重构,把所有参数都分离在json文件中

**Comment by TsingWei** [comment]
试试改成1080*1920(竖屏)

**Comment by SQNRT** [comment]
完美解决！
