### ISSUE TITLE
Device的问题

### ISSUE THREAD

**Issue by xiaoxin7534** [Jiahonzheng/JGM-Automator#18]
Device1 = 'QV7039V30X'
    Device2 = 'CB512BC4ZL'
    Device1Net = '10.21.20.105'
    Device2Net = '10.21.59.70'
    MuMu = '127.0.0.1:7555'
大佬这几个应该怎么改 用的mumu模拟器 
会报adbutils.errors.AdbError: device 'CB512BC4ZL' not found  这个未找到

**Comment by TsingWei** [comment]
用Mumu的话就把
```py
instance = Automator(Device2, up_list, harvest_filter,auto_policy=policy,auto_task=task,speedup=speed_up)
```
这行中的'Device2'改为'MuMu'
上面那堆东西是我自己的其它几个设备,测试用的
