### ISSUE TITLE
不懂就问，为什么其他坐标都是相对位置，只有绿光中心是绝对位置

### ISSUE THREAD

**Issue by qinbo1008** [Jiahonzheng/JGM-Automator#22]

**Comment by TsingWei** [comment]
其实用的时候还是相对位置啦,当时确定这些点的时候是在540*960下面找的
实际使用这些坐标的时候都先除以540和960转成相对坐标了
确实有点乱, 能用就行,这里更新了绿光的检测方式 #21

**Comment by TsingWei** [comment]
我已经改了,不再单独设置绿光检测的坐标,使用原本的建筑坐标, 检测的时候是检测建筑周围 (绿光差值通道二值化后) 的平均亮度, 返回平均亮度最大的建筑 @qinbo1008
