### ISSUE TITLE
这边更新可能有点慢,有什么bug可以换个版本试试

### ISSUE THREAD

**Issue by TsingWei** [Jiahonzheng/JGM-Automator#24]
https://github.com/TsingWei/Simple-JiaGuoMeng-Agent
这个是我一直在bug修复的版本, 作者回复pr可能有点慢(国庆都没时间开发哈哈哈)

**Comment by can1024** [comment]
设备是2340*1080的，这分辨率能改一下用吗？

**Comment by TsingWei** [comment]
> 设备是2340*1080的，这分辨率能改一下用吗？

没试过.

游戏的UI不是根据比例简单拉伸, 大概率不能用. 

如果手头没有16:9的设备,建议使用模拟器并设置成9:16的分辨率, 推荐MuMu

**Comment by can1024** [comment]
试过了，不能用，检测不到火车，自己改相对坐标能不能行？

**Comment by TsingWei** [comment]
你可以试试,
但是除了`util.py`, 还有一些坐标是直接写在`uiautomator.py`,里面的,还挺多,不嫌麻烦可以自己改改

**Comment by BackTrackCRoot** [comment]
emm 仓库的readme上少要求装了一个库 `numpy`

**Comment by TsingWei** [comment]
> emm 仓库的readme上少要求装了一个库 `numpy`

装openCV的时候会默认安装numpy

**Comment by BackTrackCRoot** [comment]
> > emm 仓库的readme上少要求装了一个库 `numpy`
> 
> 装openCV的时候会默认安装numpy

呃…… 我的没给装上 有点懵……

**Comment by TsingWei** [comment]
自己装上呗 能跑就行
