### ISSUE TITLE
企鹅机械供货判断失败率高

### ISSUE THREAD

**Issue by iciness** [Jiahonzheng/JGM-Automator#26]
企鹅机械供货判断失败率高

**Comment by TsingWei** [comment]
https://github.com/TsingWei/Simple-JiaGuoMeng-Agent
用这里的, 更新了检测方式

**Comment by xuzzzeng** [comment]
> https://github.com/TsingWei/Simple-JiaGuoMeng-Agent
> 用这里的, 更新了检测方式

用那个也不行，如果设置重启收货没问题，设置了重启就经常会漏收或者选择错目标

**Comment by iciness** [comment]
现在看起来，前后差值的方法稳定性不错
谢谢

**Comment by TsingWei** [comment]
> > https://github.com/TsingWei/Simple-JiaGuoMeng-Agent
> > 用这里的, 更新了检测方式
> 
> 用那个也不行，如果设置重启收货没问题，设置了重启就经常会漏收或者选择错目标

因为重启还没进到界面就开始判断, 所以会有这个问题,可以在重启后自己添加等待函数
