### ISSUE TITLE
不停地点击公告栏

### ISSUE THREAD

**Issue by bolycooper** [Jiahonzheng/JGM-Automator#28]

**Comment by bolycooper** [comment]
在
[Wed Oct  9 19:45:28 2019] Task finished.    ++++++
[Wed Oct  9 19:45:30 2019] No Train.
之后就一直点击公告栏

**Comment by Don-Young** [comment]
> 在
> [Wed Oct 9 19:45:28 2019] Task finished. ++++++
> [Wed Oct 9 19:45:30 2019] No Train.
> 之后就一直点击公告栏

我用的MuMu模拟器，一开始也出现这个问题，后来更改分辨率之后就解决问题了，或许是位置坐标的原因？

**Comment by liuquanpu** [comment]
更改分辨率之后就解决问题了
