### ISSUE TITLE
在判断货车到来的时候 货车来了 而货物还没显示 会误判no train 然后会触发app重启 浪费一次货车

### ISSUE THREAD

**Issue by vcfee** [Jiahonzheng/JGM-Automator#35]

**Comment by TsingWei** [comment]
你可以在`main.py`中将`speed_up`设为`false`

**Comment by BinqiZhang** [comment]
> 你可以在`main.py`中将`speed_up`设为`false`
这个问题，个人感觉这么改应该会好一点，reset app之后要过几秒钟货物才会来，然后reset app之后最好是sleep个10秒左右比较好。
--- a/automator.py
+++ b/automator.py
@@ -49,8 +49,10 @@ class Automator:
                 print("[%s] Train come."%time.asctime())
                 self.harvest(self.harvest_filter, good_id)
             else:
-                print("[%s] No Train."%time.asctime())
-                findSomething = True
+                print("[%s] No Goods! Wait 2s."%time.asctime())
+                self.swipe()
+                time.sleep(2)
+                continue

             # 再看看是不是有货没收，如果有就重启app
             good_id = self._has_good()
@@ -60,6 +62,7 @@ class Automator:
                 time.sleep(2)
                 # 重新启动app
                 self.d.app_start("com.tencent.jgm")
+                time.sleep(15)
                 continue

**Comment by TsingWei** [comment]
@BinqiZhang 好建议, 已修改@vcfee 
https://github.com/Jiahonzheng/JGM-Automator/blob/d2210cf6eb5135f6077e3cb6dc36bf43b3bb797f/automator.py#L61-L65
